export const GET_ALL_FURNITURES = 'GET_ALL_FURNITURES';
export const GET_FURNITURES_BY_NAME = 'GET_FURNITURES_BY_NAME';
export const FURNITURES_SORT_BY_NAME = 'FURNITURES_ SORT_BY_NAME';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE'
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const PREV = "PREV";
export const NEXT = "NEXT";